import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-pension-benefit-overpayment-prevention",
  "engine": "recovery",
  "title": "Pension Benefit Overpayment Prevention",
  "shortTitle": "Pension Benefit Overpayment Prevention",
  "tagline": "Prevent and resolve pension overpayments caused by eligibility, life-event, formula, offset, and beneficiary changes.",
  "industry": "Retirement Benefit Integrity",
  "buyer": "Defined-benefit plans and public pension systems",
  "uiPort": 4675,
  "apiPort": 5675,
  "accent": "#be123c",
  "currency": "USD",
  "primaryOutcome": "Pension Benefit Overpayment Prevention converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals in one accountable workflow. Prevent and resolve pension overpayments caused by eligibility, life-event, formula, offset, and beneficiary changes.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Charged or Paid Amount",
    "expectedLabel": "Evidence-Supported Amount",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Pension Benefit Overpayment Prevention evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("plan-provision-library","PBO01","Plan provision library","Execute plan provision library using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed plan provision library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Plan provision library Reference","text","PBO01-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("participant-service-history","PBO02","Participant service history","Execute participant service history using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed participant service history decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Participant service history Reference","text","PBO02-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("compensation-averaging","PBO03","Compensation averaging","Execute compensation averaging using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed compensation averaging decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Compensation averaging Reference","text","PBO03-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("benefit-formula-calculation","PBO04","Benefit formula calculation","Execute benefit formula calculation using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed benefit formula calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Benefit formula calculation Reference","text","PBO04-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("election-option-validation","PBO05","Election option validation","Execute election option validation using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed election option validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Election option validation Reference","text","PBO05-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("beneficiary-entitlement","PBO06","Beneficiary entitlement","Execute beneficiary entitlement using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed beneficiary entitlement decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Beneficiary entitlement Reference","text","PBO06-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("life-status-monitoring","PBO07","Life-status monitoring","Execute life-status monitoring using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed life-status monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Life-status monitoring Reference","text","PBO07-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("cola-calculation","PBO08","COLA calculation","Execute cola calculation using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed cola calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","COLA calculation Reference","text","PBO08-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("social-security-offset","PBO09","Social Security offset","Execute social security offset using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed social security offset decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Social Security offset Reference","text","PBO09-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("workers-compensation-offset","PBO10","Workers compensation offset","Execute workers compensation offset using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed workers compensation offset decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Workers compensation offset Reference","text","PBO10-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("payroll-payment-reconciliation","PBO11","Payroll payment reconciliation","Execute payroll payment reconciliation using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed payroll payment reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Payroll payment reconciliation Reference","text","PBO11-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("overpayment-detection","PBO12","Overpayment detection","Execute overpayment detection using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed overpayment detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Overpayment detection Reference","text","PBO12-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("recoupment-plan-workflow","PBO13","Recoupment plan workflow","Execute recoupment plan workflow using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed recoupment plan workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Recoupment plan workflow Reference","text","PBO13-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("member-appeal-evidence","PBO14","Member appeal evidence","Execute member appeal evidence using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed member appeal evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Member appeal evidence Reference","text","PBO14-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]}),
feature("plan-liability-analytics","PBO15","Plan liability analytics","Execute plan liability analytics using plan provisions, participant service, compensation, elections, beneficiaries, life status, payroll, COLAs, offsets, recoupments, and appeals.","Produce a governed plan liability analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Plan / Beneficiary","text","Plan / Beneficiary · Standard Case"],["caseReference","Plan liability analytics Reference","text","PBO15-2026-001"],["chargedAmount","Charged or Paid Amount","currency",947500],["supportedAmount","Evidence-Supported Amount","currency",795900],["domainDriver","Payment Event","select","Retirement",["Retirement","Survivor benefit","Disability pension"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"chargedAmount",subjects:["Plan provision library case","Participant service history case","Compensation averaging case","Benefit formula calculation case","Election option validation case"]})
]);
